# Generated by Django 4.0.6 on 2024-10-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('download_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
