# Generated by Django 4.0.6 on 2024-11-30 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_count', models.PositiveIntegerField(help_text='Number of frames at the start of the shift', verbose_name='Frame Count')),
                ('media_set_count', models.PositiveIntegerField(help_text='Number of media sets at the start of the shift', verbose_name='Media Set Count')),
                ('printer_life', models.PositiveIntegerField(help_text='Printer life percentage', verbose_name='Printer Life')),
                ('cash_in_envelope', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cash in Envelope')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Automatically recorded date and time of the shift start', verbose_name='Date and Time')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Photographer's Name")),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workdayapp.restaurant', verbose_name='Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frames_sold', models.PositiveIntegerField(verbose_name='Frames Sold')),
                ('photos_printed_4x6', models.PositiveIntegerField(verbose_name='Photos Printed 4x6')),
                ('postcards_printed', models.PositiveIntegerField(verbose_name='Postcards Printed')),
                ('media_sets_used', models.PositiveIntegerField(verbose_name='Media Sets Used')),
                ('cash_revenue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cash Revenue')),
                ('frames_given', models.PositiveIntegerField(verbose_name='Frames Given')),
                ('frames_damaged', models.PositiveIntegerField(verbose_name='Frames Damaged')),
                ('discount_approved', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Approved Discount Amount')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Automatically recorded date and time of the shift end', verbose_name='Date and Time')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Photographer's Name")),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workdayapp.restaurant', verbose_name='Restaurant')),
            ],
        ),
    ]
