# Generated by Django 4.0.6 on 2024-11-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workdayapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photographer',
        ),
    ]
